# Generated by Django 5.1.1 on 2024-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_restaurant_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="description",
            new_name="fd_description",
        ),
        migrations.AddField(
            model_name="fooditem",
            name="special",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="veg_or_non_veg",
            field=models.CharField(
                choices=[("veg", "Vegetarian"), ("non_veg", "Non-Vegetarian")],
                default="non_veg",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="mn_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=45),
        ),
    ]
