# Generated by Django 5.1.1 on 2024-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_rename_description_fooditem_fd_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="fd_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
