# Generated by Django 5.1.1 on 2024-10-18 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_fooditem_fd_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="veg_or_non_veg",
        ),
    ]
