# Generated by Django 5.1.1 on 2024-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.AddField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("owner", "Owner"),
                    ("chef", "Chef"),
                    ("waiter", "Waiter"),
                ],
                max_length=10,
            ),
        ),
    ]
