# Generated by Django 5.1.1 on 2024-10-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Authentication",
            "0002_remove_customuser_age_customuser_mobile_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(default="", max_length=15, unique=True),
        ),
    ]
